/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MAILCHIMP_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAILCHIMP_LIST_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAILCHIMP_TAGS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}